### ISSUE TITLE
Cache is deleted on access

### ISSUE THREAD

**Issue by aschempp** [contao/installation-bundle#11]
The install tool always deletes all caches when being accessed, even without password …

**Comment by leofeyer** [comment]
Did you check if it works when the cache is only purged after the admin has logged in?

**Comment by aschempp** [comment]
What do you mean by _does it work_ ?

**Comment by leofeyer** [comment]
See #3 for example. Will it break anything if the cache is purged later?

**Comment by aschempp** [comment]
Well the problem was that DCA files would not be read, which will obviously only be a problem if the admin is logged in…

**Comment by leofeyer** [comment]
Fixed in 67996cb3419dd5af8110be34fc9e76801486f845.
