### ISSUE TITLE
Container property is not being set for the System class

### ISSUE THREAD

**Issue by jamesdevine** [contao/installation-bundle#2]
Trying to run the latest install tool is causing the following error for me after logging in to the install tool:

```
Fatal error: Call to a member function getParameter() on a non-object in ...\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Config.php on line 125
```

It looks like the container isn't being set before `\System::getContainer()` is called. `\System::getContainer()` returns null instead of returning the container which causes the error.

A strange side effect of this error seems to be that all of my public assets are being deleted. The **originals**, not just the symlinks. For example if I have a public folder `files/images` which contains sub-folders, all of the sub-folders are deleted when I run into this error on the install tool. Also, all of the bundle assets are deleted - again, it's the original ones in `/vendor` and not just the sym-linked versions. I have to do a complete composer re-install to get them back.

I'm on Windows 10. Contao 4.0.2, install bundle 0.9.6.

**Comment by leofeyer** [comment]
See https://github.com/contao/standard-edition/issues/21.
