### ISSUE TITLE
Running the installer deletes files and destroys symlinks

### ISSUE THREAD

**Issue by Fuzzyma** [contao/installation-bundle#21]
I have to admit, that I am not sure, if this is related to the installer. However this bug happened the last time, I run the installer to update my database.

This are the facts:
- My composer links several files into the web-folder of my symfonie application
- It occured several times, that these links get deleted for a random reason but not only this: even the original content which was linked is missing after that. Only chance to get it back is to uninstall the dependency and reinstall it. It seems like there is a recursive `rm` call or something
- I noticed that behavior the last time, when I run the database update via the installer because my editor complained about a changed/removed file which was still open.

As I already said: I dont know if this is just coincident. If its not the installer then what else?
Any help is appreciated.

I should add, that this only happens for links in the web-folder. However the asset-link never got removed.

**Comment by leofeyer** [comment]
How can we reproduce the issue?

**Comment by Fuzzyma** [comment]
Because of the randomness I cant give you a good lead. I will watch our for this closer and will report as soon as I spot something.

Btw: I am on a windows machine. Could be even some odd windows bug...

**Comment by Fuzzyma** [comment]
I tried again around a bit and found that this problem seems really be related to the install tool.
To check if there are any changes in the vendor directory I run ``composer status -v` which gives me `No local changes`. After pressing `CTRL + F5` in the installation tool tab (not even logged in) I check the same command again and get this:

```
You have changes in the following dependencies:
...vendor/contao/comments-bundle:
    D src/Resources/public/approved.svg
    D src/Resources/public/pending.svg
    D src/Resources/public/replied.svg
    D src/Resources/public/style.css
...vendor/contao/newsletter-bundle:
    D src/Resources/public/icon.svg
    D src/Resources/public/style.css
```

(D means deleted)

And THATS only what composer can figure out. The symlink from modulecolumnwizard dissapeared, too - including the files in its html-folder.
I dont know why composer isnt showing that but it doesnt really matter.

Since I am not even logged into my install tool, I guess it has something to do with the `runPostInstallCommands` method. I havent checked deeper yet.

**Comment by fritzmg** [comment]
> The symlink from modulecolumnwizard dissapeared, too - including the files in its html-folder.
> I dont know why composer isnt showing that but it doesnt really matter.

The symlink isn't part of the repository, however, all the files in `vendor/contao/comments-bundle/src/Resources/public` are, that's why composer you tells you that.

You mentioned you are running on windows. What is your exact web server configuration? How are you running PHP?

**Comment by Fuzzyma** [comment]
Windows 7
php 5.6.23
xampp with vhost

I will gist you my php.ini and apache httpd.conf

// EDIT: Here we go:
- [httpd.conf](https://gist.github.com/Fuzzyma/68309a34c48ee99a6fb1b2c37a13d2cc)
- [php.ini](https://gist.github.com/Fuzzyma/da614364378c719fd207ef38a49d276e)

> The symlink isn't part of the repository, however, all the files in vendor/contao/comments-bundle/src/Resources/public are, that's why composer you tells you that.

Well not the symlink, but all files behind this link. They are missing

**Comment by leofeyer** [comment]
Did you read https://github.com/contao/docs/pull/368#issuecomment-228768913?

**Comment by Fuzzyma** [comment]
Nope. So you basically suggest to run my php as admin to allow the installTool to create symlinks?
All these symlinks already exist! I just update the database and they still get removed (and what even worse: The content of the orginal folder is deleted).

I mean: For me its not an issue anymore because I now run my database updates with the console. Still its a really strange behavior.

**Comment by leofeyer** [comment]
Yes, but it is an XAMPP issue, not a Contao issue.

**Comment by fritzmg** [comment]
If he is running PHP with FastCGI the issue should be further investigated. But of course I would need complete reproduction steps for that. So far I haven encountered anything like that.

**Comment by Fuzzyma** [comment]
Even if it is not an contao issue, it is caused by a command which comes from the install Tool. It would already be good to know which command causes this and WHY. Because creating symbolic links is one thing. But removing symlinks or even deleting files is a completely other one.

@fritzmg all I know is above. I could try to run my xamp in fastcgi though...

**Comment by fritzmg** [comment]
Due to bugs in PHP, symlink support is limited when not running PHP via FastCGI (regardless of Contao).
