### ISSUE TITLE
Backend-Sprache des im Installtool angelegten Benutzers

### ISSUE THREAD

**Issue by Mynyx** [contao/installation-bundle#26]
Wenn im Backend ein neuer Benutzer angelegt wird, ist dessen Backend-Sprache standardmäßig die Sprache, die während dem Anlegen des Benutzers eingestellt ist.

Wenn im Installtool jedoch der Benutzer angelegt wird, ist dessen Backend-Sprache stets Englisch. Stattdessen sollte hier auch die Sprache, die im Installtool verwendet wird, gesetzt werden.

**Comment by leofeyer** [comment]
Behoben in 64588df7185c6c2f8bb53fa62bbd5748cfde3ed7.
