### ISSUE TITLE
Installtool-Passwort nicht änderbar

### ISSUE THREAD

**Issue by Mynyx** [contao/installation-bundle#27]
Im Installtool besteht keine Möglichkeit das einmal gesetzt Installtool-Passwort zu ändern.

**Comment by leofeyer** [comment]
@contao/developers Brauchen wir das?

**Comment by discordier** [comment]
Nope, finde ich nicht.
Man kann in diesem Falle durchaus den Eintrag in der config entfernen.

**Comment by aschempp** [comment]
Seh ich auch so

**Comment by Mynyx** [comment]
Mit den entsprechenden Hintergrundkenntnissen kann man das natürlich manuell machen, aber diese kann man für den gewöhnlichen User doch nicht voraussetzen?

**Comment by fritzmg** [comment]
@discordier man kann alles manuell machen, wozu überhaupt ein Install Tool? ;)

**Comment by discordier** [comment]
Ich sehe den Sinn hier definitiv nicht.
Welcher Usecase ist denn hier vorhanden?

Wenn der user sein Passwort vergessen hat, dann muss er den Eintrag in der config entfernen, da er es zum aendern eingeben muss.

Und mal ehrlich, wer aendert wirklich sein Install tool password?
Das vergebe ich immer random und speicher es mir noch nichtmal, da ich viel schneller bin es zu entfernen, und neu zu vergeben.
Wenn ich fertig bin, dann aender ich den Eintrag in der `localconfig.php` auf etwas in der Art von "thou shall not pass", damit das install tool lahm gelegt ist.

Das Install tool braucht man immer nur zu upgrades, und da dann das password via GUI zu aendern, das ist meiner Meinung nach einfach unnoetig.

**Comment by ausi** [comment]
In Contao 3 ging es ja bereits. Ich sehe keinen Grund warum man diese Möglichkeit entfernen hätte sollen.

IMO sollte man ein Passwort dort wo man es vergeben kann, auch ändern können.

**Comment by leofeyer** [comment]
Ich gebe Dir grundsätzlich Recht, allerdings lässt sich das Feature auch nur deshalb umsetzen, weil wir noch in die `localconfig.php` schreiben. Die `parameters.yml` wird hingegen nicht zur Laufzeit geändert, wenn sie einmal angelegt wurde, und sobald das Installtool-Passwort dorthin wandert, fällt die Möglichkeit der Änderung wieder weg. Daher können wir es IMO auch gleich weglassen.

**Comment by fritzmg** [comment]
War nicht der Plan, dass man mit der Zeit _mehr_ Einstellungen wieder über das Backend machen können wird? Oder passiert das dann bspw. nur mehr über den Contao Manager?

**Comment by aschempp** [comment]
Die Aussage von Leo halte ich für falsch. Das Passwort wird in der localconfig bleiben, solange es das Install-Tool gibt. Später wird es über den Contao Manager laufen. 

Ich finde das Feature trotzdem nicht nötig, das Install-Tool ist für Administrationen und in den extrem seltenen Fällen reicht auch die localconfig.

**Comment by leofeyer** [comment]
> Die Aussage von Leo halte ich für falsch. Das Passwort wird in der localconfig bleiben, solange es das Install-Tool gibt. Später wird es über den Contao Manager laufen.

Da hast Du natürlich Recht. Das Installtool-Passwort wird nie in die `parameters.yml` kommen.

**Comment by fritzmg** [comment]
@discordier 

> Welcher Usecase ist denn hier vorhanden?

Überall dort wo man ein Passwort setzen kann, wird man es evt. auch verändern wollen. Usecases von nicht erfahrenen Contao Benutzern fallen dir da bestimmt welche ein. Selbst als erfahrener Benutzer kann es für dich sicher mal convenient oder evt. sogar notwendig sein, das Passwort über das Install Tool zu ändern.

> Und mal ehrlich, wer aendert wirklich sein Install tool password?
> Das vergebe ich immer random und speicher es mir noch nichtmal, da ich viel schneller bin es zu entfernen, und neu zu vergeben.
> Wenn ich fertig bin, dann aender ich den Eintrag in der localconfig.php auf etwas in der Art von "thou shall not pass", damit das install tool lahm gelegt ist.

Du solltest hier nicht von dir auf Andere schließen. Nur weil du das so machst, heißt das ja nicht, dass das der Großteil auch so macht.

**Comment by backbone87** [comment]
Soll das denn im Sinne einer "Passwort vergessen" Funktion sein oder einfach nur "Passwort ändern"?

**Comment by xchs** [comment]
> In Contao 3 ging es ja bereits. Ich sehe keinen Grund warum man diese Möglichkeit entfernen hätte sollen.
> IMO sollte man ein Passwort dort wo man es vergeben kann, auch ändern können.

+1

**Comment by leofeyer** [comment]
Wie am 10. August 2017 in Mumble besprochen, muss das Installtool-Passwort nicht zwangsläufig in der `localconfig.php`-Datei stehen (es kann z.B. auch in der `config.yml` unter `contao.localconfig.installPassword` stehen), daher ist eine "Passwort ändern"-Funktion technisch sehr aufwändig und steht in keiner Relation zum Aufwand. Besonders vor dem Hintergrund, dass das Installtooll auf lange Sicht vom Contao-Manager abgelöst werden soll.
