### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by Toflar** [contao/installation-bundle#3]
The install.php runs in production mode. This means that whenever you add or edit e.g. DCA files in the "dev" environment, the installation bundle will not notice this because the DcaExtractor checks for the production file cache to exist.

**Comment by leofeyer** [comment]
So what is your suggestion here?

**Comment by Toflar** [comment]
I think it makes no sense to run the installer in production mode where it caches things...

**Comment by leofeyer** [comment]
Symfony also caches things in dev mode, doesn't it?

**Comment by Toflar** [comment]
Well the main issue is that our `Installer` does not display any changes because it always checks for `prod/cache/sql`. So you cannot develop via `app_dev.php` and then update the database.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
Running the installer in dev mode seems right to me.

Is it possible to have a different database connection in dev mode? If so, it should be possible to choose if the installer should run in dev or prod mode.

**Comment by Toflar** [comment]
Of course it is possible. It's even possible to have your own `foobar` environment :-)

**Comment by Toflar** [comment]
Simple solution: `install.php`  and `install_dev.php`. But I don't really see why it should run in `prod` environment to be honest.

**Comment by aschempp** [comment]
I don't think its about the environment. The DCA cache is not necessarily build in prod, but it can also be built in dev. Maybe the install tool should use a custom resource finder that ignores the cache?

**Comment by leofeyer** [comment]
Fixed in 556aff1fcb17f483ef5feb801662d518661ccb71. The `kernel.cache_dir` is now set to a non existing folder, so the Contao 3 framework will always loop through the source files and never load a potentially outdated cache file.
