### ISSUE TITLE
Installtool Entsperren

### ISSUE THREAD

**Issue by Mynyx** [contao/installation-bundle#30]
Nach mehrfacher falscher Passworteingabe erscheint folgende Fehlermeldung:

> Es ist ein Fehler aufgetreten
> Das Installtool wurde gesperrt!
> Aus Sicherheitsgründen wurde das Installtool gesperrt, nachdem dreimal hintereinander ein falsches Passwort eingegeben wurde. Um es zu entsperren, führen Sie den Befehl app/console doctrine:cache:clear contao.cache auf der Konsole aus.

```
$ php app/console doctrine:cache:clear contao.cache
Clearing the cache for the contao.cache provider of type Doctrine\Common\Cache\FilesystemCache
```

Das Installtool ist jedoch weiterhin gesperrt.

**Comment by stefansl** [comment]
Das hat nichts mit dem Cache zu tun. Da steht ein Eintrag in der tl_member Tabelle, dass der Benutzer gesperrt ist. Entweder darin den lock auf 0 setzen oder 5 Minuten warten.

**Comment by Mynyx** [comment]
Der Login zum Installtool hat mit der tl_member Tabelle doch nichts zu tun?

**Comment by stefansl** [comment]
Sorry, stimmt. In dem Fall wird das über die /system/localconfig.php gesteuert. 
$GLOBALS['TL_CONFIG']['installCount'] = 3;

siehe https://github.com/contao/installation-bundle/blob/master/src/InstallTool.php#L106-L117

**Comment by Mynyx** [comment]
Nein, auch mit der `localconfig.php` hat das nichts zu tun.

Siehe https://github.com/contao/installation-bundle/blob/master/src/InstallTool.php#L124

**Comment by fritzmg** [comment]
I can confirm that running

```
php app/console doctrine:cache:clear contao.cache
```

will _not_ clear the `contao.cache` and thus will not reset the `login-count`. Only

```
php app/console cache:clear --env=prod
```

will work - this clears the whole cache though, not just `contao.cache`.

**Comment by leofeyer** [comment]
Ja, das Installtool läuft im `prod` Environment, daher muss man lokal `--env=prod` anhängen. Auf dem Live-Server sollte automatisch das `prod` Environment ausgewählt sein.

**Comment by fritzmg** [comment]
@leofeyer but if `cache:clear` is the right command, then the description in the Install Tool is wrong. It tells you to execute

```
php app/console doctrine:cache:clear contao.cache
```

Which does not work.

https://github.com/contao/installation-bundle/blob/1.1.5/src/Resources/translations/messages.en.xlf#L19

**Comment by fritzmg** [comment]
This needs to be updated in the transifex translations I am guessing.

**Comment by fritzmg** [comment]
> Ja, das Installtool läuft im prod Environment, daher muss man lokal --env=prod anhängen. Auf dem Live-Server sollte automatisch das prod Environment ausgewählt sein.

Ah, jetzt verstehe ich, warum das Kommando ursprünglich nicht funktioniert hat.

Automatisch wird aber nicht zwischen lokalen und live Server unterschieden (wie auch), man muss dafür in seiner Shell die Umgebungsvariable `SYMFONY_ENV` selbst auf `prod` setzen.

@Mynyx du musst `php app/console doctrine:cache:clear contao.cache --env=prod` benutzen oder zuvor `SYMFONY_ENV` auf `prod` in deiner Shell Umgebung setzen (http://stackoverflow.com/a/9571729/374996)
