### ISSUE TITLE
install tool does not (cannot) display errors of install commands

### ISSUE THREAD

**Issue by fritzmg** [contao/installation-bundle#32]
If some errors happen while running `InstallationController::runPostInstallCommands` for example, the errors will not be displayed to the user and the installation might be left in an incomplete state without him knowing. For instance, if some errors happen while creating the symlinks, e.g.:

```
 ------- ------------------------ --------------------------------------------------------------------------------------------------------------------------------------------------- 
          Symlink                  Target / Error                                                                                                                                     
 ------- ------------------------ --------------------------------------------------------------------------------------------------------------------------------------------------- 
  ERROR   system/themes/flexible   Unable to create symlink due to error code 1314: 'A required privilege is not held by the client'. Do you have the required Administrator-rights?  
  ERROR   web/assets               Unable to create symlink due to error code 1314: 'A required privilege is not held by the client'. Do you have the required Administrator-rights?  
  ERROR   web/system/themes        Unable to create symlink due to error code 1314: 'A required privilege is not held by the client'. Do you have the required Administrator-rights?  
  ERROR   system/logs              Unable to create symlink due to error code 1314: 'A required privilege is not held by the client'. Do you have the required Administrator-rights?  
 ------- ------------------------ ---------------------------------------------------------------------------------------------------------------------------------------------------
```

These errors are catched by the command and then written to the `SymfonyStyle` object, which creates the styled output for the command line. That output will go nowhere though, since `InstallationController::runPostInstallCommands` uses a `NullOutput`

``` php
$command->run(new ArgvInput([]), new NullOutput());
```

So they are not visible nor logged anywhere.

May be these post-install-commands should be put in an `InstallService` for example, so that errors can be handled differently by the callers? The `contao:symlinks` command would then call these functions from the `InstallService`, catch the errors and display them on the command line as usual, while the `InstallationController` can catch the errors and then display them in the Install Tool instead.

**Comment by leofeyer** [comment]
Implemented in 848084bb7eb48e51f202e67c00330082a0667db0.

<img width="817" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19352058/b2c7404a-915e-11e6-8358-67b74cc17416.png">

**Comment by fritzmg** [comment]
Btw. the same problem exists on various other places, where commands are invoked. For instance, if the creation of symlinks fails here: [core-bundle/src/Resources/contao/dca/tl_files.php#L685](https://github.com/contao/core-bundle/blob/4.2.4/src/Resources/contao/dca/tl_files.php#L685) there will be no entry in the symfony log or system log indicating what the problem might have been.

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@8003d04aaca8bf1ccb09a7be254fce6d512fb6f0.
