### ISSUE TITLE
Allow more special characters in database names

### ISSUE THREAD

**Issue by nkirstein** [contao/installation-bundle#35]
As per [this](https://github.com/contao/installation-bundle/commit/a0a4d8fb15abedd7b320bbb28aa5402d73f6aad1) commit the install tool no longer allows special characters in database names except `$` and `_` . That can be a problem because some hosters don't allow you to choose database names freely. On HostEurope WebPacks, for example, database names always start with `wp123456789-`. You can choose what comes after the hyphen but you can't get rid of the hyphen itself. Please allow for such situations.

**Comment by fritzmg** [comment]
Related: https://github.com/contao/core-bundle/issues/593

**Comment by leofeyer** [comment]
Even though it is a duplicate, at least the ticket is in the correct repo. 😄

**Comment by leofeyer** [comment]
I have reverted the changes in 28e8efc1e3e3acd833994411039cfaffe7b7a7de.
