### ISSUE TITLE
Cannot modify fields with onload_callback

### ISSUE THREAD

**Issue by Toflar** [contao/installation-bundle#4]
The `onload_callback` does not seem to be considered in the `Installer` or the `DcaExtractor`, that's why field modifications there are not being considered.

**Comment by leofeyer** [comment]
This is the same behavior as in Contao 3, isn't it?

**Comment by Toflar** [comment]
Not sure but if it is, then I guess it should be fixed. What's your opinion?

**Comment by leofeyer** [comment]
I'm not sure. Is it a bugfix? If yes, how will it affect the existing extensions?

**Comment by Toflar** [comment]
Well the changes are quite obvious. Right now you cannot modify `sql` definitions by an`onload_callback` because the `Installer` ignores it. Either the users have always been wondering why this is and found other solutions (like the `loadDataContainer` hook) or they've just never tried. It is actually a bug fix but it can potentially cause issues if somebody relied on the fact that onload_callbacks are not executed during DB update mode (which is obviously not API, so we can change it).

I guess we have to balance pros and cons here... @contao/developers

**Comment by discordier** [comment]
Wait a sec, you want to modify the SQL information when a "model" is loaded?
What the hell is that for an usecase?

**Comment by leofeyer** [comment]
As discussed on Mumble on October 14th, this ticket can be closed.
