### ISSUE TITLE
InstallTool logException

### ISSUE THREAD

**Issue by digitalingenieur** [contao/installation-bundle#41]
In Contao Managed Version the path to the log file should be something like

`$this->rootDir.'/../var/logs/prod-'.date('Y-m-d').'.log'`

in InstallTool.php, Line 395

**Comment by ghost** [comment]
The issue has been moved to contao/manager-bundle#17.

**Comment by leofeyer** [comment]
Fixed in d3bc4e615f11a0ccb56e11ff63a6fafd30d7396f.
