### ISSUE TITLE
Cannot install managed edition

### ISSUE THREAD

**Issue by Toflar** [contao/installation-bundle#43]
Not sure but I guess this should solve it:

```diff
    public function installAction()
    {
        if ($this->container->has('contao.framework')) {
+            try {
                $this->container->get('contao.framework')->initialize();
+            } catch (IncompleteInstallationException $e) {}
        }
```

/cc @aschempp @leofeyer

**Comment by leofeyer** [comment]
As briefly discussed in Slack, this will not work, because the framework would not be fully booted. Fixed in contao/core-bundle@8a79abf5d7a9f2e50eb0961bcc8f99ae404792ac now.
