### ISSUE TITLE
Install-Tool can't handle ORM without migrations

### ISSUE THREAD

**Issue by aschempp** [contao/installation-bundle#46]
If Doctrine Migrations is not installed, the install tool will not detect ORM entities and suggest to drop the respective tables.

I really doubt anyone is actively using ORM but not the CLI for DB, but who knows…

**Comment by leofeyer** [comment]
Is there anything we can/should do to fix this?

**Comment by aschempp** [comment]
Pretty sure there is something we can do, but I don't have time to dig the code atm.

**Comment by aschempp** [comment]
See contao/core-bundle#725
