### ISSUE TITLE
Also ask for the mail settings

### ISSUE THREAD

**Issue by leofeyer** [contao/installation-bundle#5]
This is the follow-up ticket of contao/core-bundle#363.

**Comment by leofeyer** [comment]
This seems to be unnecessary, because Symfony is configured to use the PHP `mail()` function by default. Only if someone wants to use an SMTP server instead, they have to adjust the `parameters.yml` file. Don't know if we need to provide a GUI for that though?

@contao/developers /cc

**Comment by Toflar** [comment]
If we can, we should I think.

**Comment by leofeyer** [comment]
And if so, we should discuss where to offer the GUI. In the install tool? In the back end settings?

**Comment by leofeyer** [comment]
As discussed on Mumble on November 5th, this will be solved as soon as we start using Tenside instead of the install tool.
