### ISSUE TITLE
Integrate real DB migrations

### ISSUE THREAD

**Issue by backbone87** [contao/installation-bundle#50]
Having a real DB migration framework would open up for a better extension maintenance

possible solution:
- directly use an existing db migration framework (problem: what concepts they provide in terms of plugin based db schemas)
- greatly increase doctrines schema tool features to work with procedures, triggers and views (and ofc contribute this back to the doctrine project)
- build a migrations system on our own
- just use the hook (which is currently missing :D) and let the developer feel the pain

**Comment by Toflar** [comment]
I think no. 3 should never be an option. To me, a combination of 1 and 2 should always be the way to go. We cannot stem yet another project ;)

**Comment by leofeyer** [comment]
We now have a migrations framework (Contao 4.9+). 🎉
