### ISSUE TITLE
Re-add the backend link

### ISSUE THREAD

**Issue by aschempp** [contao/installation-bundle#6]
now that we have the real container, it should be possible to re-add the link to the backend in the install tool, right?

**Comment by leofeyer** [comment]
I don't think that this was the reason why I have removed it. I will try to re-add it and maybe I will remember :)

**Comment by leofeyer** [comment]
Re-added in 9b5d6d4782f05f9d6a87c46c252d90bd962acbed.

**Comment by aschempp** [comment]
Will this work if the installation is not yet complete?

**Comment by leofeyer** [comment]
The link will not be displayed before the `parameters.yml` file exists and the real kernel can be booted.

**Comment by aschempp** [comment]
:+1:

**Comment by aschempp** [comment]
Unfortunately, this does not work. If the installation is in a subfolder (and that's supported because the install tool runs in `dev` environment), the route will always point to `/contao` without the subpath. Should we use `route(…)` instead of `path(…)` (or what was the name)?

**Comment by leofeyer** [comment]
I'll check.

**Comment by leofeyer** [comment]
Fixed in d1f4d093980df352bd49b2f49160f1d3793efd8e.
