### ISSUE TITLE
schema manager fails with unknown db types

### ISSUE THREAD

**Issue by m-vo** [contao/installation-bundle#62]
I am in the process of migrating a Contao 3.5 installation to version 4 that contains some tables with ``POINT`` and other geometric data types (mysql spatial extension). 

When opening the install tool a ``DBALException`` is thrown because doctrine unfortunately doesn't know anything gemoetric column types:
>Unknown database type point requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

This only happens if the table has a column of an 'unknown type' and the table name starts with ``tl_``.

My quick fix for that was to add a custom mapping to my ``config.yml`` like so...
```yml
doctrine:
  dbal:
    mapping_types:
      point: blob
```
... but isn't there a better (more general) way? Why does doctrine need to know about those columns for the migration?

**Comment by dmolineus** [comment]
Maybe you should have a look at https://github.com/creof/doctrine2-spatial

**Comment by leofeyer** [comment]
@aschempp /cc

**Comment by aschempp** [comment]
I think that error originates from Doctrine, so we can't do much about it. @dmolineus has probably the right solution.
