### ISSUE TITLE
CacheWarmup missing?

### ISSUE THREAD

**Issue by rabauss** [contao/installation-bundle#63]
We use isotope with contao 4 and now we had several problems with missing dca-files in cache after cache:clear. then isotope cannot load the relations correctly (https://github.com/isotope/core/issues/1832).
after calling cache:warmup everything is fine because the cache is recreated.

so I researched in the code and found the 'cache_clearer' in the InstallationController. Now I understand, that after every Installation the problem occured.

Why is there no cache_warmer in the installation-bundle???

**Comment by fritzmg** [comment]
If the cache is cleared without warmup (clearing the cache _with_ warmup is deprecated now), the cache should be automatically built on the next request.

**Comment by fritzmg** [comment]
There is a `cache:warmup` in the post-update and -install script of the manager-bundle: https://github.com/contao/manager-bundle/blob/4.4.2/src/Composer/ScriptHandler.php#L38

You are right though. Any time you open the install tool and login, the prod cache is deleted. I am not sure it is wise to do that in a regular request. How can one be sure that the cache is built within the same request again?

**Comment by rabauss** [comment]
yes, i know that with warmup is deprecated.
in my installation the cachedir/contao/dca is not recreated after cache:clear

**Comment by fritzmg** [comment]
I can confirm that. The internal cache of Contao (config, dca, languages & sql) is __not__ generated under the following circumstances:

* Clearing the cache manually by deleting `va/cache/prod` and then making a front end or back end request.
* Clearing the cache via `cache:clear --no-warmup` and then making a front end or back end request.

The internal Cache of Contao will only be generated when using either one of these commands:

* `cache:clear` (deprecated)
* `cache:warmup`

**Comment by fritzmg** [comment]
So may be it should be changed like this:
```diff
-            $this->container->get('cache_clearer')->clear($realCacheDir);
+            $this->container->get('cache_warmer')->warmUp($realCacheDir);
```
Unless clearing the cache is necessary before warmup - then just add the warmup after.

**Comment by aschempp** [comment]
The Contao internal cache is *optional*, meaning Contao works without it (lower performance though). That's why the cache is not build if you simply clear it, which also helps with development because otherwise you would need to rebuild the cache on every file change.

Not sure what we do about the install tool though.

**Comment by leofeyer** [comment]
> The internal Cache of Contao will only be generated when using either one of these commands:
> 
>* `cache:clear` (deprecated)
>* `cache:warmup`

Yes, and we are using `cache:clear` at the moment. I know it is deprecated, but it will continue to work until one day we update to Symfony 4.

**Comment by leofeyer** [comment]
> The internal Cache of Contao will only be generated when using either one of these commands:
> 
>* `cache:clear` (deprecated)
>* `cache:warmup`

Yes, that is because the Contao cache warmer has been declared optional. @contao/developers Should we make the Contao cache warmer required?

**Comment by fritzmg** [comment]
Otherwise, whenever a user logs into the install tool, the internal cache of Contao will never be built, without the user knowing about it. Currently you have to execute `cache:warmup` manually after you used the install tool everytime.

And if you solely use the Contao Manager then your only option is doing a package update after using the install tool. 

Which would result in quite a ridiculous workflow ;) 

1. Install an extension/bundle via the Contao Manager, which will run a composer update
2. Open the install tool
3. Run a composer update via the Contao Manager again

**Comment by aschempp** [comment]
There is a menu option to rebuild the cache from the Contao Manager!

**Comment by fritzmg** [comment]
Right, didn't notice that! But still, currently there is no feedback about whether or not the internal cache is built yet (like there used to in Contao 3).

**Comment by rabauss** [comment]
if the cache is optional, so why is my isotope crashing with "field is not related"???

**Comment by Toflar** [comment]
Because maybe Isotope is not correctly loading what it needs. If it relies on the cache to be present, this is a bug.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 10th, 2017, the install tool needs to warm up the cache.

**Comment by leofeyer** [comment]
See #66.
