### ISSUE TITLE
Install tool cache warm up in dev environment

### ISSUE THREAD

**Issue by dmolineus** [contao/installation-bundle#67]
Since https://github.com/contao/installation-bundle/issues/63 the install tool warmups the cache. When being in dev environment I usually don't warm up the cache. Calling the install tool will always warm up the cache. Shouldn't it only be warmed up in the prod environment?

**Comment by leofeyer** [comment]
We have just talked about it in Mumble. The cache needs to be warmed up, however the optional warmers must only be warmed up if not in debug mode.

**Comment by leofeyer** [comment]
Fixed in 31d8e0d150779c8d0072a603719d77bd0db84280.
