### ISSUE TITLE
Use the MicroKernel (maybe)

### ISSUE THREAD

**Issue by aschempp** [contao/installation-bundle#8]
Symfony has added a new `MicroKernel` in v2.8
https://github.com/symfony/symfony/pull/15990

This could be useful for our case instead of the strange `unbootable` kernel. Needs investigation though.

**Comment by leofeyer** [comment]
IMHO we do not need this, because the micro kernel adds routing, which we do not use in the install tool. And the unbootable kernel is long gone anyway.
