### ISSUE TITLE
Check all innodb_large_prefix requirements

### ISSUE THREAD

**Issue by ghost** [contao/installation-bundle#80]
<a href="https://github.com/fmoessbauer"><img src="https://avatars3.githubusercontent.com/u/9655545?v=4" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/core/issues/8484#issuecomment-354433604) by @fmoessbauer
December 29th, 2017, 12:21 GMT

Ah, I was referring to the changelog on contao.org: https://contao.org/de/changelog/versions/4.5.html

For me, all settings where missing, however the install tool detected that `innodb_large_prefix` was not enabled. I then enabled that and the install tool showed the DB updates. However when starting the DB updates, the error appeared in the logs, and hence the tool was not able to get past the change to innoDB.

**Comment by leofeyer** [comment]
We should check all three requirements depending on the MySQL version.

**Comment by christian-schattat** [comment]
Nachdem das Installtool den Hinweis

> Die `innodb_large_prefix-Option` ist nicht aktiv!

ausgegeben hat, habe ich den Hoster darum gebeten, die Option zu aktivieren. Der Hoster hat mich anschliessend darauf aufmerksam gemacht, dass die Option veraltet ist:

> die option `innodb_large_prefix` ist als 'deprecated' markiert und kann unter anderem deshalb auf unseren shared-hostings eher nicht aktiviert werden. gibt es keine möglichkeit diesen fehler anderweitig zum umgehen?

Im [MySQL-Handbuch](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix) habe ich folgende Aussage gelesen:

> `innodb_large_prefix` is deprecated and will be removed in a future release. `innodb_large_prefix` was introduced in MySQL 5.5 to disable large index key prefixes for compatibility with earlier versions of InnoDB that do not support large index key prefixes.

Es ist eigentlich kein Problem, da in der [Readme](https://github.com/contao/managed-edition#innodb-large-prefix) eine Alternative steht. Dennoch wäre die Umstellung auf InnoDB im Rahmen des Updates auf Contao 4.5 schon nett gewesen. Bitte diesen Issue daher eher als Info zu möglichen Hosting-Einschränkungen und nicht als Problem verstehen. ;-)

**Comment by leofeyer** [comment]
Die Aussage "ist deprecated und kann daher nicht aktiviert werden" ist völliger Blödsinn. Das Flag ist deprecated, weil spätere MySQL-Versionen die Option immer verwenden und man halt dann kein Flag mehr braucht. Deshalb kann man das Flag in MySQL 5.5 trotzdem nutzen!

**Comment by leofeyer** [comment]
Behoben in 1bdf0ec2c8bc9472ee9b3cdb8c6e0f2dd0696659.

**Comment by m-vo** [comment]
Even with `innodb_large_prefix` enabled a problem can occur if the default `ROW_FORMAT` does not get set in the query. 

For instance: With MariaDB < 10.2 the `ROW_FORMAT` defaults to `COMPACT` and throws `ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.` even with  `innodb_large_prefix`  enabled.
  
Those who stumble across this - you can use the following setting to enforce entity creation with the dynamic fomat attribute set:
```yaml
doctrine:
    dbal:
        default_table_options:
            row_format: DYNAMIC
```
