### ISSUE TITLE
install tool fails in dev environment if user table does not exist

### ISSUE THREAD

**Issue by m-vo** [contao/installation-bundle#82]
When running the install tool via the `app_dev` entry point there is a query to the user table that might not exist (yet) and therefore will produce an exception. This renders the install tool unusable until the table gets created.

```
An exception occurred while executing 'SELECT * FROM tl_user WHERE username='Administrator' LIMIT 0,1':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'abc.tl_user' doesn't exist

Doctrine\DBAL\Exception\ TableNotFoundException 
```

The query originates here: https://github.com/contao/core-bundle/blob/4.5/src/Resources/contao/library/Contao/User.php#L502 which gets triggered somewhere when `schemaProvider->createSchema();` is executed.

**Comment by aschempp** [comment]
That's very interesting. The install tool does explicitly not have a firewall (https://github.com/contao/manager-bundle/blob/master/src/Resources/skeleton/app/security.yml#L21-L23) and should therefore not load. Also, where does `Administrator` come from?

Two ideas:
 - `Administrator` is your Windows username?
 - You're using Basic Authentication with a user `Administrator`?

**Comment by m-vo** [comment]
I'm on linux with no Basic Auth, but you're absolutely right: There is no reference to `Administrator` in the code. 

It turns out, that `Administrator` was the admin account earlier on before the tables had been dropped. So this seems to be some dreaded cache (or maybe session) issue (even on `app_dev`?). I've come across this problem some days before as well during development but I'm unfortunately not sure how to reproduce it. 

If this problem does not occur on a fresh installation (and that is what it looks like) this sure is no problem.

**Comment by aschempp** [comment]
Can you find out (backtrace) who called `User::loadUserByUsername`?

**Comment by m-vo** [comment]
Damn, there is no full stacktrace in the logs and right now I can't get it to fail. :-/
I'll run the debugger if it appears again.
