### ISSUE TITLE
Schema diff fails with MariaDB 10.2

### ISSUE THREAD

**Issue by m-vo** [contao/installation-bundle#83]
I upgraded to MariaDB 10.2.12 (10.2.12-MariaDB-10.2.12+maria~xenial) on my dev machine and noticed that now the schema diff stopped working properly (contao bundles 4.5.1, doctrine/dbal 2.6.3). 

I haven't had time to investigate further but here is what I am seeing: There are lots of entries that request to alter tables (even without the tables existing) and - if existing - columns.

This is what's happening to a new install:

![screenshot_20180105_181554](https://user-images.githubusercontent.com/5305677/34620093-8efaba0a-f244-11e7-9fd3-e54820a6c9d2.png)

![screenshot_20180105_184512](https://user-images.githubusercontent.com/5305677/34621228-99f44210-f248-11e7-8c7f-03d45fb156c8.png)

@leofeyer I noticed that you referred to the same or a similar problem [here](https://github.com/contao/core-bundle/issues/918#issuecomment-315851936) but I'm not sure if there was a solution. 

Also there seems to be a related issue in the [community forum](https://community.contao.org/de/showthread.php?69256-Install-Tool-%E2%80%93-Datenbank-Aktualisierung&highlight=title+title).

-----

By the way: Having `innodb_strict_mode` disabled and/or `sql_mode` set to just `NO_ENGINE_SUBSTITUTION` doesn't make a difference.

**Comment by m-vo** [comment]
Had a quick look in the debugger. It's the same issue as in here: https://github.com/contao/core-bundle/issues/918#issuecomment-315855902

So `_default` equals `"''"` in `$fromSchema` vs. `""` in $toSchema.

(Also: doctrine entities get created successfully but then are missing in the `$fromSchema`. Not sure if this had worked before.)

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/918#issuecomment-315855902

**Comment by fritzmg** [comment]
@leofeyer all tickets (including https://jira.mariadb.org/browse/MDEV-13132) are closed now, yet the issue still exists.

**Comment by m-vo** [comment]
I am still not sure if it's a MariaDB  or a doctrine issue. But it looks like it is the latter as doctrine seems to only support MariaDB 10.2. as of v2.7 which is not released yet. 

I can confirm that using the current doctrine/dbal dev-master branch solves the default value problem but it could still take a long time until a stable branch will get released. So unfortunately Contao is not compatible to Maria DB 10.2 right now, right? :-/

**Comment by leofeyer** [comment]
Correct, you need Doctrine 2.7 (not yet released).
