### ISSUE TITLE
Calling install tool throws error after update to Contao 4.5.1

### ISSUE THREAD

**Issue by Seefahrer** [contao/installation-bundle#85]
Upon updating Contao to 4.5.1 under MAMP 4.2.1, the install tool throws following error:

`[2018-01-07 11:42:47] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"http://carlito/contao/install","method":"GET"} []
[2018-01-07 11:42:47] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: strtolower() expects parameter 1 to be string, null given at /Users/georg/Websites/carlito/vendor/contao/installation-bundle/src/InstallTool.php:274)"} []
`

The error is caused by line 274 in /vendor/contao/installation-bundle/src/InstallTool.php:

`$vok = 'mariadb' === strtolower($vendor) ? '10.2' : '5.7.7';`

**Comment by aschempp** [comment]
Duplicate of #84

**Comment by Seefahrer** [comment]
oops, did not realise that above issue has already been addressed in #84.
After replacing line 274 with the updated version, everything is fine!
