### ISSUE TITLE
Installation with MariaDB>10.3.1 not possible

### ISSUE THREAD

**Issue by agoat** [contao/installation-bundle#87]
The variable `innodb_large_prefix` is deprecated since MariaDB 10.2 and is now removed in version **10.3.1**.

When trying to install contao with a MariaDB 10.3.1+ server the install tool is complaining to set the `innodb_large_prefix` variable which is not available anymore. 

When changing the corresponding lines in the [InstallTool.php](https://github.com/contao/installation-bundle/blob/master/src/InstallTool.php#L261) to something like this:
```php
        if ('InnoDB' === $options['engine'] && 0 === strncmp($options['collate'], 'utf8mb4', 7) && version_compare($version, '10.3.1', '<')) {
            $row = $this->connection
                ->query("SHOW VARIABLES LIKE 'innodb_large_prefix'")
                ->fetch(\PDO::FETCH_OBJ)
            ;
```

The installation process can then continue, but will try to update all table columns again and again..

![mariadb103-problem](https://user-images.githubusercontent.com/1402434/36800985-22dfe312-1cb1-11e8-94b9-2d2104468d6f.jpg)

After changing also the corresponding lines in [DCASchemaProvider.php](https://github.com/contao/core-bundle/blob/3cdcebbe3a68881b2b55c4d92cd333b04a04c940/src/Doctrine/Schema/DcaSchemaProvider.php#L452-L459) in the core-bundle, I was able to login and at the first glance everything was working.

**Comment by m-vo** [comment]
btw Contao/doctrine does not even support 10.2, see https://github.com/contao/installation-bundle/issues/83#issuecomment-355745013

**Comment by agoat** [comment]
Looks like contao resp. symfony (using Doctrine) has general problems with MariaDB ..

**Comment by aschempp** [comment]
> The variable innodb_large_prefix is deprecated since MariaDB 10.2 and is now removed in version 10.3.1.

What is the reason for them removing it? Is it enabled by default? Can you point to a page where you found that information?

**Comment by leofeyer** [comment]
The information is correct. The whole point of deprecating was being able to remove it. 😄 

> innodb_large_prefix is deprecated and will be removed in a future release.

* https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix
* https://mariadb.com/kb/en/library/xtradbinnodb-server-system-variables/#innodb_large_prefix

@agoat What does `SHOW VARIABLES LIKE 'innodb_large_prefix'` return on MariaDB 10.3.1? Does it throw an error?

**Comment by agoat** [comment]
> What does SHOW VARIABLES LIKE 'innodb_large_prefix' return on MariaDB 10.3.1? Does it throw an error?

MariaDB returns an empty result (Tested with phpMyAdmin on a MariaDB 10.3.5 server).

But the result of
```php
            $row = $this->connection
                ->query("SHOW VARIABLES LIKE 'innodb_large_prefix'")
                ->fetch(\PDO::FETCH_OBJ)
            ;
```
is `false`.

**Comment by agoat** [comment]
MariaDB 10.3.1+ and MySQL 5.8?+ always use 3072 bytes.

**Comment by leofeyer** [comment]
So basically:

* If `false === $row`: The option does no longer exist -> 3072.
* If `in_array(strtolower($row->Value), ['1', 'on'])`: The option is enabled -> 3072.
* Else: The option is disabled -> 767.

**Comment by leofeyer** [comment]
Fixed in contao/core-bundle@e5b39f7078f955a6387529d46bd67ecc724736bf.

**Comment by agoat** [comment]
The [InstallTool.php](https://github.com/contao/installation-bundle/blob/master/src/InstallTool.php#L267) is checking the `innodb_large_prefix` variable and currently prevents installation with MariaDB 10.3.1+.

But the check for `innodb_large_prefix` is removed in the 4.5 branch (https://github.com/contao/installation-bundle/commit/c829c203ac266cb78aafaf12dcf5f4a87e46ab54). Will this be included in the next release?

**Comment by leofeyer** [comment]
Yes.
