### ISSUE TITLE
Supply alternative for runonce.php

### ISSUE THREAD

**Issue by m-vo** [contao/installation-bundle#96]
Currently the only way to provide database migrations for an extension is to provide a `runonce.php` (right?).

This has several drawbacks:
- IMHO the system should not delete source files
- does not fit class loading scheme
- constructor DI / using services does not work
- boilerplate code needed for instantiation
- simply does not work / throws exception when file is not 'inside' the contao root (which is the case 
while developing with symlinked packages)
 
**Idea 1:**
The contao-bundle database updates are managed with the files inside `src/Database` that implement `Contao\InstallationBundle\Database\AbstractVersionUpdate`. Can't we use those for extensions as well? Searching for classes that implement this exeact interface and executing `shouldBeRun()` / `run()` on them. 

(I'm not aware of how exactly the install tool will change in the near future regarding the manager though.)

**Idea 2:**
At least let's fix the problem, that symlinked packages do not work.

**Comment by m-vo** [comment]
Ok, just found out there is also the `sqlCompileCommands` hook that can be used. That's a usable approach. But still I think this could be generalized.

**Comment by leofeyer** [comment]
Ideas for replacing the `runonce.php` concepts are discussed here: https://github.com/contao/core-bundle/issues/1223
