### ISSUE TITLE
handle mod_article_teaser and mod_article_plain selection

### ISSUE THREAD

**Issue by fritzmg** [contao/installation-bundle#97]
In Contao 3 you were able to select a variety of custom template for articles, including `mod_article_plain` and `mod_article_teaser` which were removed in Contao 4.

However, this will lead to an
```
Could not find template "mod_article_plain"
```
error after upgrading to Contao 4 if these template were previously set as a `customTpl` manually (for whatever reason) and no such template is present as a custom template.

Thus may be `Version400Update` should check whether or not a custom template with these names are present and if not, `tl_module.customTpl` should be emptied for these records.

**Comment by ghost** [comment]
The issue has been moved to contao/contao#21.
